baseURL = 'https://www.naturaktiv-boesingen.de'
languageCode = 'de'
title = 'NaturAktiv Bösingen e.V.'
theme = 'hugo-theme-cleanwhite'
copyright = 'NaturAktiv Bösingen e.V. | VR 727115'

#frontpage pagination
[pagination]
pagerSize = 10

enableRobotsTXT = true
buildFuture = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
home = ["HTML", "RSS"]

[params]
	header_image = "img/naturaktiv-hero.jpg"
	slogan = "Natur aktiv erleben"
	SEOTitle = "NaturAktiv Bösingen e.V."
	SEODescription = "NaturAktiv Bösingen e.V. - Eingetragener Wanderverein in Bösingen"
	SEOKeywords = "NaturAktiv Bösingen, Wandern, Hofboschhütte, Harzwald, Naturschutz, 78662 Bösingen, VR 727115"
	description = "Eingetragener Verein für aktives Wandern und Naturschutz"
	author = "NaturAktiv Bösingen e.V."
	keywords = "Wandern, Schwarzwald, Schwäbische Alb, Bösingen"

	logo = "/img/logo-naturaktiv.png"
	favicon = "/favicon.ico"

	# CSS wird jetzt via Hugo Pipes mit Fingerprinting eingebunden (siehe layouts/partials/head.html)

	image_404 = "img/404-bg.jpg"
	omit_categories = true

	# Sidebar settings
	sidebar_about_description = ""
	sidebar_avatar = "img/logo-naturaktiv.png"

	featured_tags = false
	featured_condition_size = 1

	friends = false
	bookmarks = false
	about_me = true
	
	# Termine-Filterung: Wie viele Tage zurück sollen Termine angezeigt werden?
	termine_days_back = 4

	[[params.additional_menus]]
	title = "Termine"
	href = "/termine"

	[[params.additional_menus]]
	title = "Rückblick"
	href = "/rueckblick"

	[[params.additional_menus]]
	title = "Hofboschhütte"
	href = "/hofboschhuette"

	[[params.additional_menus]]
	title = "Dokumente"
	href = "/dokumente"
	
	[[params.additional_menus]]
	title = "Impressum"
	href = "/impressum"

	[params.social]
	rss = true
	email = "info@naturaktiv-boesingen.de"
